# Generated by Django 5.1 on 2024-08-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='idData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearbookId', models.CharField(default='', max_length=10)),
                ('otherSelectedPeople', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
